DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS user;


CREATE TABLE user (
userid INTEGER UNSIGNED UNIQUE PRIMARY KEY AUTO_INCREMENT,
email varchar(80) NOT NULL UNIQUE,
`password` TEXT NOT NULL,
`name` varchar(50),
female BOOLEAN,
phone_number char(10) DEFAULT NULL
);


CREATE TABLE trips (
id INTEGER UNSIGNED UNIQUE PRIMARY KEY AUTO_INCREMENT,
trip_date DATE,
pickup_point varchar(100) NOT NULL,
drop_point varchar(100) NOT NULL,
vehicle TINYINT,
num_people TINYINT,
gender_filter BOOLEAN,
user_1 INTEGER UNSIGNED UNIQUE NOT NULL,
user_2 INTEGER UNSIGNED UNIQUE DEFAULT NULL,
user_3 INTEGER UNSIGNED UNIQUE DEFAULT NULL,
user_4 INTEGER UNSIGNED UNIQUE DEFAULT NULL,
user_5 INTEGER UNSIGNED UNIQUE DEFAULT NULL,
user_6 INTEGER UNSIGNED UNIQUE DEFAULT NULL,
user_7 INTEGER UNSIGNED UNIQUE DEFAULT NULL,
user_8 INTEGER UNSIGNED UNIQUE DEFAULT NULL,
resolved BOOLEAN DEFAULT FALSE,
FOREIGN KEY (user_1) REFERENCES user (userid),
FOREIGN KEY (user_2) REFERENCES user (userid),
FOREIGN KEY (user_3) REFERENCES user (userid),
FOREIGN KEY (user_4) REFERENCES user (userid),
FOREIGN KEY (user_5) REFERENCES user (userid),
FOREIGN KEY (user_6) REFERENCES user (userid),
FOREIGN KEY (user_7) REFERENCES user (userid),
FOREIGN KEY (user_8) REFERENCES user (userid)
);